### ISSUE TITLE
Should we remove .dummy?

### ISSUE THREAD

**Issue by ftomassetti** [mps-lwc-16/mps-lwc-16#1]
I am not sure what is the role of .dummy. Is it present just to make git include the directory? For that purpose you may want to use .gitignore instead

**Comment by eugenschindler** [comment]
Yes, I think the .dummy is only for git to include a directory. Can you remove it and make it such that .gitignore handles that? Then I can see how that is done and learn something new :)

**Comment by ftomassetti** [comment]
Done
The trick is just to create a file named .gitignore to make git aware of the directory
